name: Update tokens

on: workflow_dispatch

env:
  FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
  PRIMITIVE_TOKENS_FILE_KEY: ${{ secrets.TOKENS__PRIMITIVE_TOKENS_FILE_KEY }}
  ADMIN_TOKENS_FILE_KEY: ${{ secrets.TOKENS__ADMIN_TOKENS_FILE_KEY }}

jobs:
  update:
    name: Update tokens
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --prefer-offline

      - name: Update tokens
        run: pnpm --filter @shopware-ag/meteor-tokens run start

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update tokens
          committer: Dennis Mader <${{ secrets.ICON_KIT__COMMITTER }}>
          author: Dennis Mader <${{ secrets.ICON_KIT__COMMITTER }}>
          branch: update-tokens
          delete-branch: true
          branch-suffix: timestamp
          title: Update tokens
          assignees: Weltraumakustik
